name: Build and Test
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Test
      run: npm run test
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: DecimalSystem
        path: dist/
